# Generated by Django 5.2.13 on 2026-06-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('display_order', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamEnrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_enrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.TextField()),
                ('difficulty', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('requirement_text', models.TextField()),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('starting_topology', models.JSONField(blank=True, null=True)),
                ('goal_topology', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('starting_topology', models.JSONField()),
                ('goal_topology', models.JSONField()),
            ],
            options={
                'db_table': 'laboratories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleEnrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'module_enrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleProfessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coordinator', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'module_professors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('account_type', models.TextField()),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.JSONField(blank=True, null=True)),
                ('submitted_topology', models.JSONField(blank=True, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.users')),
                ('academic_title', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('ai_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_model', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'professors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lms.users')),
                ('enrollment_year', models.IntegerField()),
                ('study_group', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
